### ISSUE TITLE
something confusing about examples in transpose conv?

### ISSUE THREAD

**Issue by fengshi-cherish** [vdumoulin/conv_arithmetic#32] opened 2021-09-17 08:50 UTC
![image](https://user-images.githubusercontent.com/22573687/133753858-4c3d2050-df09-4f91-a190-9b8aad5dd60b.png)
why it is equivalent to convolving a 3 * 3 kernel over a 2 * 2 input not over 3*3 input?

**Comment by fvisin** [comment] 2021-10-05 11:16
Duplicate of https://github.com/vdumoulin/conv_arithmetic/issues/18.
The caption is indeed incorrect and should say 3x3 input.

**Closed as completed by fvisin** 2021-10-05 11:16 UTC
Labels: duplicate
