### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by bjpcjp** [vdumoulin/conv_arithmetic#23] opened 2018-11-06 14:41 UTC
make all_animations fails on Ubuntu Linux 14.04 as follows:

```
./bin/produce_figure arithmetic no_padding_no_strides 0 --input-size=4 --output-size=2 --padding=0 --kernel-size=3 --stride=1 
Traceback (most recent call last):
  File "./bin/produce_figure", line 272, in <module>
    compile_figure(which_, name, step, **args_dict)
  File "./bin/produce_figure", line 223, in compile_figure
    if '! LaTeX Error' in stdoutdata or '! Emergency stop' in stdoutdata:
TypeError: a bytes-like object is required, not 'str'
make: *** [pdf/no_padding_no_strides_00.pdf] Error 1
```

**Comment by fvisin** [comment] 2018-11-06 17:30
The error is likely due to differences between python 2 and python 3. Can you try and run the code with python 2?

**Comment by fvisin** [comment] 2018-11-21 13:37
Closing because there has been no reply in two weeks. Also, unfortunately we don't have much bandwidth to support these kind of code issues anyway.

**Closed as completed by fvisin** 2018-11-21 13:37 UTC

**Comment by LinaShanghaitech** [comment] 2019-01-24 01:20
> The error is likely due to differences between python 2 and python 3. Can you try and run the code with python 2?
As what you say, it's an error caused by python3 .

**Comment by ffrmns** [comment] 2021-01-09 06:33
> The error is likely due to differences between python 2 and python 3. Can you try and run the code with python 2?

Thanks, I change python symlink at /usr/bin to python2 and works!
```
sudo rm /usr/bin/python
sudo ln -s /usr/bin/python2 /usr/bin/python
```
Just don't forget to revert it backs when you need it!
